README.md

Point Sample Report to htmlpreview.github.io

---

.github/workflows/Release.yml

Added PSSharedGoods module

---

.github/workflows/Release.yml
AsBuiltReport.Microsoft.AD.psd1
README.md
Src/Private/Get-AbrADDomain.ps1
Src/Private/Get-AbrADDomainObject.ps1
Src/Private/Get-AbrADForest.ps1

Push this code to let the user know the module installation commands

Initial 0.7.2 version release

---

AsBuiltReport.Microsoft.AD.psd1
CHANGELOG.md
Samples/Sample Microsoft AD As Built Report.html
Src/Private/Get-AbrADCARoot.ps1
Src/Private/Get-AbrADDCRoleFeature.ps1
Src/Private/Get-AbrADDomainLastBackup.ps1
Src/Private/Get-AbrADDomainObject.ps1
Src/Private/Get-AbrADKerberosAudit.ps1
Src/Private/Get-AbrADSecurityAssessment.ps1
Src/Private/Get-RequiredFeature.ps1
Src/Private/Get-RequiredModule.ps1
Src/Public/Invoke-AsBuiltReport.Microsoft.AD.ps1

- Improved validation of module dependencies
- HomeLab

Improved validation of module dependencies

---

AsBuiltReport.Microsoft.AD.psd1
README.md
Src/Private/Get-AbrADSiteReplication.ps1
Src/Private/SharedUtilsFunctions.ps1
Src/Public/Invoke-AsBuiltReport.Microsoft.AD.ps1

Removed PSSharedGoods/PSWriteColor module dependency

Removed PSSharedGoods/PSWriteColor module dependency

---

AsBuiltReport.Microsoft.AD.psd1
CHANGELOG.md
Src/Private/Get-AbrADDomainObject.ps1

- Access well known groups via SID to include international names and expand them to localized group names.
- Removed PSSharedGoods/PSWriteColor module dependency
- Fixes [#42](https://github.com/AsBuiltReport/AsBuiltReport.Microsoft.AD/issues/42)
- #42
- Access well known groups via SID to include international names and expand them to localized group names.
- Removed PSSharedGoods/PSWriteColor module dependency
- HomeLab

v0.7.4 WIP

---

Src/Private/SharedUtilsFunctions.ps1
Src/Public/Invoke-AsBuiltReport.Microsoft.AD.ps1

Final modification for v0.7.4 release

Final modification for v0.7.4 release

---

Src/Private/SharedUtilsFunctions.ps1

[Fix PSScriptAnalyzer warnings](https://github.com/AsBuiltReport/AsBuiltReport.Microsoft.AD/commit/1017b030b07fced225d4b3bb21fe78ed30cf8839)

Fix PSScriptAnalyzer warnings

---

Src/Public/Invoke-AsBuiltReport.Microsoft.AD.ps1

Fix report version validation process

Fix report version validation process

---

Src/Public/Invoke-AsBuiltReport.Microsoft.AD.ps1

Domain section lack Health Check after v0.7.6 update

---

AsBuiltReport.Microsoft.AD.psd1
Src/Private/Get-AbrADDCDiag.ps1
Src/Private/Get-AbrADDomainController.ps1
Src/Private/Get-AbrADInfrastructureService.ps1
Src/Public/Invoke-AsBuiltReport.Microsoft.AD.ps1

bump modified file to v0.7.7

---

.github/workflows/Release.yml
AsBuiltReport.Microsoft.AD.psd1

removed dhcp from modules

---

Src/Private/Get-AbrADDNSInfrastructure.ps1

spelling change on a single word

spelling: talbe -> table

---

Src/Private/Get-AbrADCACRLSetting.ps1
Src/Private/Get-AbrADDomainController.ps1
Src/Private/Get-AbrADDomainObject.ps1
Src/Private/Get-AbrADFSMO.ps1
Src/Private/Get-AbrADOU.ps1
Src/Private/Get-AbrADSecurityAssessment.ps1
Src/Private/Get-AbrPKISection.ps1

Fix CodeQL Alerts

---

.github/workflows/Release.yml
AsBuiltReport.Microsoft.AD.psd1

Added Diagrammer.Microsoft.Ad module

Added Diagrammer.Microsoft.Ad module

---

AsBuiltReport.Microsoft.AD.psd1
CHANGELOG.md
README.md
Src/Private/Get-AbrADForest.ps1
Src/Public/Invoke-AsBuiltReport.Microsoft.AD.ps1

- Removed Graphviz install check code.
- HomeLab

Added Graphviz libraries to local module folder. (No need to manually install Graphviz)

---

CHANGELOG.md

Fix ChangeLog

---

CHANGELOG.md
Src/Private/Get-AbrADDFSHealth.ps1
Src/Private/Get-AbrADDomain.ps1
Src/Private/Get-AbrADDomainController.ps1
Src/Private/Get-AbrADDomainObject.ps1
Src/Private/Get-AbrADOU.ps1
Src/Private/Get-AbrADSecurityAssessment.ps1
Src/Private/Get-AbrADSite.ps1
Src/Private/Get-AbrADTrust.ps1
Src/Private/Get-AbrDomainSection.ps1
Src/Public/Invoke-AsBuiltReport.Microsoft.AD.ps1

Fix Issues & Added Foreign Security Principals section
- Fix #154 
- Fix #153 
- Fix #152 
- Fix #151 
- Fix #150 
- HomeLab

Fix Issues & Added Foreign Security Principals section

---

AsBuiltReport.Microsoft.AD.psd1

Increalse Diagrammer.Microsoft.AD module version v0.2.3

Increalse Diagrammer.Microsoft.AD module version v0.2.3

---

AsBuiltReport.Microsoft.AD.psd1
CHANGELOG.md

Increase AsBuiltReport.Core module version requirements v1.4.0

Increase AsBuiltReport.Core module version requirements v1.4.0

---

CHANGELOG.md
Src/Private/SharedUtilsFunctions.ps1

- Fix [#190](https://github.com/AsBuiltReport/AsBuiltReport.Microsoft.AD/issues/190)
- Fix [#191](https://github.com/AsBuiltReport/AsBuiltReport.Microsoft.AD/issues/191)
- Fix ConvertTo-HashToYN cmdlet not generating an ordereddictionary output

Fix multiple issues

---

Src/Private/SharedUtilsFunctions.ps1

Fix CodeQL #38

---

AsBuiltReport.Microsoft.AD.psd1
CHANGELOG.md
LICENSE
Src/Private/Get-AbrADCARoot.ps1
Src/Private/Get-AbrADDCDiag.ps1
Src/Private/Get-AbrADDFSHealth.ps1
Src/Private/Get-AbrADDomainController.ps1
Src/Private/Get-AbrADDomainObject.ps1
Src/Private/Get-AbrADForest.ps1
Src/Private/Get-AbrADHardening.ps1
Src/Private/Get-AbrADSite.ps1
Src/Private/Get-AbrADTrust.ps1
Src/Private/Get-AbrDHCPinAD.ps1
Src/Private/Get-AbrDomainSection.ps1
Src/Private/SharedUtilsFunctions.ps1
Src/Public/Invoke-AsBuiltReport.Microsoft.AD.ps1

- Add Site Inventory diagram to the Replication section
- Add Certificate Authority diagram
- Move Circular Group Membership section to $InfoLevel.Domain level 4
- Increase AsBuiltReport.Core to v1.4.2
- Increase Diagrammer.Core minimum requirement
- Increase Diagrammer.Microsoft.AD minumum requirement
- Fix error message during DC discovery and WinRM connection
- Fix Get-WinADLastBackup cmdlet not returning AD partitions when the report generation machine is not part of the same domain or forest as the target domain controller
- Fix Certificate Authority section displaying content when no data is available
- Fix DHCP Infrastructure section not identifying if the server is a Domain Controller
- Fix Enterprise Root Certificate Authority section not displaying table descriptions

v0.9.3 public release

---

AsBuiltReport.Microsoft.AD.psd1
CHANGELOG.md
Src/Private/Get-AbrADDCDiag.ps1
Src/Private/Get-AbrADDCRoleFeature.ps1
Src/Private/Get-AbrADDFSHealth.ps1
Src/Private/Get-AbrADDNSZone.ps1
Src/Private/Get-AbrADDomainController.ps1
Src/Private/Get-AbrADFSMO.ps1
Src/Private/Get-AbrADGPO.ps1
Src/Private/Get-AbrADHardening.ps1
Src/Private/Get-AbrADInfrastructureService.ps1
Src/Private/Get-AbrADSecurityAssessment.ps1
Src/Private/Get-AbrADSite.ps1
Src/Private/Get-AbrADSiteReplication.ps1
Src/Private/Get-AbrDomainSection.ps1
Src/Private/SharedUtilsFunctions.ps1
Src/Public/Invoke-AsBuiltReport.Microsoft.AD.ps1

Update scripts to version 0.9.4 and improve session handling
- Updated version numbers in multiple scripts to 0.9.4.
- Changed session names from static values to dynamic values based on the Domain Controller name for better clarity and management.
- Removed unnecessary session cleanup commands to streamline the code.
- Commented out non-functional sections in Get-AbrDomainSection.ps1 and SharedUtilsFunctions.ps1 for future reference.
- Enhanced error handling and logging for session establishment in Invoke-AsBuiltReport.Microsoft.AD.ps1.

v0.9.4 WIP
